### PR TITLE
➕ create profile page

### PR DESCRIPTION
**Pull request by Himanshuiiit**

### CODE REVIEW

**Review by darshanhande11 — CHANGES_REQUESTED** [review]
@Himanshuiiit Please fix the following:

1. User should not be able to enter more than 200 characters in the Bio TextBox Field.

image

2. Earning Address Field is not editable. Make it editable so that user can change the earning address.

image

3. User is able to elongate the textbox of Bio. Make it fixed to 3 rows.

image

4. After uploading the picture, the picture should be visible in the circular div before it.

**Comment by darshanhande11** [comment]
@Himanshuiiit Please do the following fixes:

1. When I add a new earning address and then click on the copy icon, the older address gets copied to clipboard.
2. For potrait images (height > width), the image overflows from the circular div

image

3. Compare the button of figma and localhost, the text should be bold and use the appropriate font, add the horizontal padding.

Figma:
image

**Review by darshanhande11 — APPROVED** [review]

**Comment by solankidivyam** [comment]
@Himanshuiiit Do you think the title "Profile" is little left sided?

Dev : 
Screenshot 2022-12-26 at 9 07 17 AM

Design :
Screenshot 2022-12-26 at 9 08 29 AM


Also, the card for creator should be a little wider, should increase horizontal size. The card does not update when clicked on save changes. @darshanhande11 you talked about live update, is it not to be implemented??

Screenshot 2022-12-26 at 9 09 26 AM

**Comment by Himanshuiiit** [comment]
> @Himanshuiiit Do you think the title "Profile" is little left sided?
> 
> Dev : 
> Screenshot 2022-12-26 at 9 07 17 AM
> 
> Design :
> Screenshot 2022-12-26 at 9 08 29 AM
> 
> 
> Also, the card for creator should be a little wider, should increase horizontal size. The card does not update when clicked on save changes. @darshanhande11 you talked about live update, is it not to be implemented??
> 
> Screenshot 2022-12-26 at 9 09 26 AM
> 

Sir, the title is aligned with the title of content, Actually I had asked about this design issue to Darshan sir on the day one of making this design, this is happening due to different aspect ratio of design viewport and our screen ...

Regarding the card being wider, I will do that now.

And the save buttons features will be implemented using back-end so for now I have just stored the form data in different variables only...

**Comment by nlok5923** [comment]
@Himanshuiiit Good work

Here are some changes which are needed.

- Changes are quite visible between design and development

Design
image

Dev
image

Differences
- margin between card and input component are quite large.
- the save button should be inline with the bottom of card.
- Also the content in the card should update realtime based on the user inputs. and in case there is no input is missing fix it with some dummy (semantically relevant) text.

**Comment by Himanshuiiit** [comment]
> @Himanshuiiit Good work
> 
> Here are some changes which are needed.
> 
> - Changes are quite visible between design and development
> 
> Design
> image
> 
> Dev
> image
> 
> Differences
> - margin between card and input component are quite large.
> - the save button should be inline with the bottom of card.
> - Also the content in the card should update realtime based on the user inputs. and in case there is no input is missing fix it with some dummy (semantically relevant) text.
> 

Sir,
Regarding this card updation, I had asked @darshanhande11 about it on the first day, and he said that the card will be updated via back-end so for now I was just asked to just keep the data of form in states which will be used once we will be having the backend.
So please once look after it.

And regarding other issues I am working on it...

**Comment by darshanhande11** [comment]
@Himanshuiiit Yeah! I assumed that updates would occur post hitting the save changes button. But, now we have collectively agreed upon updating the data on the card concurrently as the user writes in the Input fields. That would look great and also help the user to preview the data on the card before doing a write on the backend. So, you can work on the feature of real time updation of data on the card.

**Review by solankidivyam — APPROVED** [review]

**Comment by nlok5923** [comment]
@Himanshuiiit good work just a few changes in design needed then we are gtg

- Please make share button inline with Extent logo on card
image

- Also place inline share button with address as well as in figma design
image

**Comment by nlok5923** [comment]
@Himanshuiiit can you please fix this in case of empty bio the address is overflown.
image

**Comment by Himanshuiiit** [comment]
> @Himanshuiiit can you please fix this in case of empty bio the address is overflown.
> image
> 

Should I truncate it... Or should I make the font size smaller sir? Or should I just fix the should I just fix the size of the card only?

**Comment by darshanhande11** [comment]
@Himanshuiiit You can increase the min-height of the card (to take care of empty bio case) to accommodate the overflow of address.

**Comment by Himanshuiiit** [comment]
> @Himanshuiiit You can increase the min-height of the card (to take care of empty bio case) to accommodate the overflow of address.

Yes sir, have done the same...
Please check

**Review by nlok5923 — APPROVED** [review]

**Pull request merged**
