### PR TITLE
Create Draft Page + Table

### PR DESCRIPTION
**Pull request by Vijay-K-2003**
Screenshot from 2022-12-20 17-55-34

### CODE REVIEW

**Review by darshanhande11 — CHANGES_REQUESTED** [review]
@Vijay-K-2003 

* Please compare the styling of the draft page in the Figma to that of the localhost and make it look more like the design. Take a closer look at the font-family, font-weight, font-color, padding and font-size in the figma to make the frontend more like it.

Figma:
image
Localhost:
image

**Comment by Vijay-K-2003** [comment]
Screenshot from 2022-12-21 10-53-56

**Comment by darshanhande11** [comment]
@Vijay-K-2003 Still not like the design, I ran it on my localhost. On my device this is the frontend I am seeing.
<br/>
<br/>
image

**Comment by darshanhande11** [comment]
@Vijay-K-2003 I have just fetched the changes on main into your branch. It is breaking probably due to the removal of ChakraProvider from Index.tsx. Please fix the styling as it is breaking:
image

This is was the styling before merging main into your branch:
image

**Comment by nlok5923** [comment]
@Vijay-K-2003 implement the design in such a way that when creator simultaneously switches back and forth from content page to draft page he should only be able to spot differences only in the data not in page layout.

**Comment by nlok5923** [comment]
@Vijay-K-2003 i would recommend you to assign an appropriate title to your pr. try using the prefixes like feat, fix, chore, doc etc based on the changes this pr is introducing. It improves the development history of project.

**Comment by darshanhande11** [comment]
@Vijay-K-2003 Please do the following fixes:

* When I am hovering the cursor in the area between Preview and GoLive Button, the cursor is still pointer whereas it should be arrow, since there is nothing to click.
* Remove the padding around the Go Live Button's Icon, due to which the Inner Button elements are not centre alligned properly.

Figma:
image

Localhost:
image

**Review by darshanhande11 — APPROVED** [review]

**Comment by solankidivyam** [comment]
@Vijay-K-2003 

The area between the top and where "Draft" starts it is quite big in my screen, check if it is the case in yours, make a little adjustment and ping me to check the change


Nice

**Comment by nlok5923** [comment]
LGTM 👍

**Review by nlok5923 — APPROVED** [review]

**Review by solankidivyam — APPROVED** [review]

**Pull request merged**
